services:
  - type: web
    name: wildlife-safari
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn wildlife_safari_project.wsgi:application --workers 2
    envVars:
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: PYTHON_VERSION
        value: "3.11.6"
    envVars:
      - key: DEBUG
        value: "True"  # Change to False after testing
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost,127.0.0.1,f55f416eeb72.ngrok-free.app"
      # M-Pesa Sandbox Variables
      - key: MPESA_CONSUMER_KEY
        value: 'AXWLaqAjwtHGPFiqa0AG7iliPv0Uc34tHAYtYICSO2AOh9HA' 
      - key: MPESA_CONSUMER_SECRET
        value: 'kkf7CUn1RO4GjJn5ENkBaUlZbdtWlfjudb3ekna03A56z5Vnd6HIoYOTSmKqx4Ef'
      - key: MPESA_PASSKEY
        value: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919' 
      - key: MPESA_CALLBACK_URL
        value: "https://wildlife-safari.onrender.com/api/mpesa-callback/"