# Generated by Django 5.2.4 on 2025-07-24 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_safari_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='country',
        ),
        migrations.AddField(
            model_name='tourist',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist',
            name='second_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
