# Generated by Django 5.2.4 on 2025-07-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlife_safari_app', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('best_time_to_visit', models.CharField(max_length=100)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='places/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
